### ISSUE TITLE
Straighten out LFS on ported UnxTools

### ISSUE THREAD

**Issue by ckormanyos** [ckormanyos/real-time-cpp-toolchains#15]

**Comment by ckormanyos** [comment]
The tools are stored as diffs since the LFS handling is wrong on the tools in [ref_app/tools/Util/msys64/usr/bin](https://github.com/ckormanyos/real-time-cpp-toolchains/tree/master/ref_app/tools/Util/msys64/usr/bin)

**Comment by ckormanyos** [comment]
Repaired in 7361c4c94f19a11b2378c11b5fa3bd0c52eddcc6

Hi Iliass (@imahjoub) hopefully, this has finally been properly repaired. We should do independent verification of the `*nix`-tool integrity now.

**Comment by imahjoub** [comment]
Hi Chris (@ckormanyos ), I just downloaded the tools locally and they seem to work properly.

**Comment by ckormanyos** [comment]
Thanks Iliass (@imahjoub). That is good so that problem seems to be solved...
